-file(
    "/Users/alind/.local/share/mise/installs/erlang/28.2/lib/parsetools-2.7/include/leexinc.hrl",
    0
).
%%
%% %CopyrightBegin%
%%
%% SPDX-License-Identifier: BSD-2-Clause
%%
%% Copyright (c) 2008,2009 Robert Virding. All rights reserved.
%% Copyright Ericsson AB 2009-2025. All Rights Reserved.
%%
%% Redistribution and use in source and binary forms, with or without
%% modification, are permitted provided that the following conditions
%% are met:
%%
%% 1. Redistributions of source code must retain the above copyright
%% notice, this list of conditions and the following disclaimer.
%% 2. Redistributions in binary form must reproduce the above copyright
%% notice, this list of conditions and the following disclaimer in the
%% documentation and/or other materials provided with the distribution.
%%
%% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
%% "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
%% LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
%% FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
%% COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
%% INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
%% BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
%% LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
%% CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
%% LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
%% ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
%% POSSIBILITY OF SUCH DAMAGE.
%%
%% %CopyrightEnd%
%%

%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(cucumis_gherkin_scanner).

-export([string/1, string/2, token/2, token/3, tokens/2, tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 30
).
-export([content/1]).
-export([file/1]).

%--- API -----------------------------------------------------------------------

content(Content) when is_binary(Content) ->
    {ok, Tokens, _EndLoc} = ?MODULE:string(binary_to_list(Content)),
    Tokens;
content(Content) when is_list(Content) ->
    content(iolist_to_binary(Content)).

file(Filename) ->
    case file:read_file(Filename) of
        {ok, Content} -> content(Content);
        {error, enoent} -> error({file_not_found, Filename});
        {error, Reason} -> error({could_not_load_file, Filename, Reason})
    end.

%--- Internal ------------------------------------------------------------------

statement(Prefix, Loc, String) ->
    {
        keyword_to_atom(Prefix),
        Loc,
        string:trim(b(string:prefix(string:trim(String), Prefix)), both, ": ")
    }.

keyword_to_atom(Keyword) ->
    binary_to_atom(b(string:replace(string:to_lower(Keyword), " ", "_"))).

b(IOList) -> iolist_to_binary(IOList).

tags(String) ->
    [
        T
     || <<"@", T/bytes>> <- re:split(string:trim(String), "[[:space:]]+"),
        T =/= <<>>
    ].

-file(
    "/Users/alind/.local/share/mise/installs/erlang/28.2/lib/parsetools-2.7/include/leexinc.hrl",
    47
).

format_error({illegal, S}) -> ["illegal characters ", io_lib:write_string(S)];
format_error({user, S}) -> S.

%% string(InChars) ->
%% string(InChars, Loc) ->
%% {ok,Tokens,EndLoc} | {error,ErrorInfo,EndLoc}.
%% Loc is the starting location of the token, while EndLoc is the first not scanned
%% location. Location is either Line or {Line,Column}, depending on the "error_location" option.

string(Ics) ->
    string(Ics, 1).
string(Ics, L0) ->
    string(Ics, L0, 1, Ics, []).
string(Ics, L0, C0, Tcs, Ts) ->
    case do_string(Ics, L0, C0, Tcs, Ts) of
        {ok, T, {L, _}} ->
            {ok, T, L};
        {error, {{EL, _}, M, D}, {L, _}} ->
            EI = {EL, M, D},
            {error, EI, L}
    end.

% No partial tokens!
do_string([], L, C, [], Ts) ->
    {ok, yyrev(Ts), {L, C}};
do_string(Ics0, L0, C0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, C0, 0, reject, 0) of
        % Accepting end state
        {A, Alen, Ics1, L1, _C1} ->
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        % Accepting transition state
        {A, Alen, Ics1, L1, _C1, _S1} ->
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        % After a non-accepting state
        {reject, _Alen, Tlen, _Ics1, _L1, _C1, _S1} ->
            {error, {{L0, C0}, ?MODULE, {illegal, yypre(Tcs, Tlen + 1)}},
                {L0, C0}};
        {A, Alen, Tlen, _Ics1, L1, C1, _S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            C2 = adjust_col(Tcs, Alen, C1),
            string_cont(Tcs1, L2, C2, yyaction(A, Alen, Tcs, L0, C0), Ts)
    end.

%% string_cont(RestChars, Line, Col, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/5}).

string_cont(Rest, Line, Col, {token, T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T | Ts]);
string_cont(Rest, Line, Col, {token, T, Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T | Ts]);
string_cont(Rest, Line, Col, {end_token, T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T | Ts]);
string_cont(Rest, Line, Col, {end_token, T, Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T | Ts]);
string_cont(Rest, Line, Col, skip_token, Ts) ->
    do_string(Rest, Line, Col, Rest, Ts);
string_cont(Rest, Line, Col, {skip_token, Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, Ts);
string_cont(_Rest, Line, Col, {error, S}, _Ts) ->
    {error, {{Line, Col}, ?MODULE, {user, S}}, {Line, Col}}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCol,AccAction,AccLen}

token(Cont, Chars) ->
    token(Cont, Chars, 1).
token(Cont, Chars, Line) ->
    case do_token(Cont, Chars, Line, 1) of
        {more, _} = C ->
            C;
        {done, Ret0, R} ->
            Ret1 =
                case Ret0 of
                    {ok, T, {L, _}} -> {ok, T, L};
                    {eof, {L, _}} -> {eof, L};
                    {error, {{EL, _}, M, D}, {L, _}} -> {error, {EL, M, D}, L}
                end,
            {done, Ret1, R}
    end.

do_token([], Chars, Line, Col) ->
    token(yystate(), Chars, Line, Col, Chars, 0, Line, Col, reject, 0);
do_token(
    {token, State, Line, Col, Tcs, Tlen, Tline, Tcol, Action, Alen}, Chars, _, _
) ->
    token(
        State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Action, Alen
    ).

%% token(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1, Alen1, Ics1, L1, C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol));
        %% Accepting transition state, can take more chars.

        % Need more chars to check
        {A1, Alen1, [], L1, C1, S1} ->
            {more, {token, S1, L1, C1, Tcs, Alen1, Tline, Tcol, A1, Alen1}};
        % Take what we got
        {A1, Alen1, Ics1, L1, C1, _S1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol));
        %% After a non-accepting state, maybe reach accept state later.

        % Need more chars to check
        {A1, Alen1, Tlen1, [], L1, C1, S1} ->
            {more, {token, S1, L1, C1, Tcs, Tlen1, Tline, Tcol, A1, Alen1}};
        % No token match
        {reject, _Alen1, Tlen1, eof, L1, C1, _S1} ->
            %% Check for partial token which is error.
            Ret =
                if
                    Tlen1 > 0 ->
                        {error,
                            {
                                {Tline, Tcol},
                                ?MODULE,
                                %% Skip eof tail in Tcs.
                                {illegal, yypre(Tcs, Tlen1)}
                            },
                            {L1, C1}};
                    true ->
                        {eof, {L1, C1}}
                end,
            {done, Ret, eof};
        % No token match
        {reject, _Alen1, Tlen1, Ics1, _L1, _C1, _S1} ->
            Error = {{Tline, Tcol}, ?MODULE, {illegal, yypre(Tcs, Tlen1 + 1)}},
            {done, {error, Error, {Tline, Tcol}}, Ics1};
        % Use last accept match
        {A1, Alen1, Tlen1, _Ics1, L1, _C1, _S1} ->
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            token_cont(Tcs1, L2, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol))
    end.

%% token_cont(RestChars, Line, Col, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/4}).

token_cont(Rest, Line, Col, {token, T}) ->
    {done, {ok, T, {Line, Col}}, Rest};
token_cont(Rest, Line, Col, {token, T, Push}) ->
    NewRest = Push ++ Rest,
    {done, {ok, T, {Line, Col}}, NewRest};
token_cont(Rest, Line, Col, {end_token, T}) ->
    {done, {ok, T, {Line, Col}}, Rest};
token_cont(Rest, Line, Col, {end_token, T, Push}) ->
    NewRest = Push ++ Rest,
    {done, {ok, T, {Line, Col}}, NewRest};
token_cont(Rest, Line, Col, skip_token) ->
    token(yystate(), Rest, Line, Col, Rest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {skip_token, Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {error, S}) ->
    {done, {error, {{Line, Col}, ?MODULE, {user, S}}, {Line, Col}}, Rest}.

%% tokens(Continuation, Chars) ->
%% tokens(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Error,AccAction,AccLen}

tokens(Cont, Chars) ->
    tokens(Cont, Chars, 1).
tokens(Cont, Chars, Line) ->
    case do_tokens(Cont, Chars, Line, 1) of
        {more, _} = C ->
            C;
        {done, Ret0, R} ->
            Ret1 =
                case Ret0 of
                    {ok, T, {L, _}} -> {ok, T, L};
                    {eof, {L, _}} -> {eof, L};
                    {error, {{EL, _}, M, D}, {L, _}} -> {error, {EL, M, D}, L}
                end,
            {done, Ret1, R}
    end.

do_tokens([], Chars, Line, Col) ->
    tokens(yystate(), Chars, Line, Col, Chars, 0, Line, Col, [], reject, 0);
do_tokens(
    {tokens, State, Line, Col, Tcs, Tlen, Tline, Tcol, Ts, Action, Alen},
    Chars,
    _,
    _
) ->
    tokens(
        State,
        Chars,
        Line,
        Col,
        Tcs ++ Chars,
        Tlen,
        Tline,
        Tcol,
        Ts,
        Action,
        Alen
    );
do_tokens(
    {skip_tokens, State, Line, Col, Tcs, Tlen, Tline, Tcol, Error, Action,
        Alen},
    Chars,
    _,
    _
) ->
    skip_tokens(
        State,
        Chars,
        Line,
        Col,
        Tcs ++ Chars,
        Tlen,
        Tline,
        Tcol,
        Error,
        Action,
        Alen
    ).

%% tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol,Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1, Alen1, Ics1, L1, C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(
                Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts
            );
        %% Accepting transition state, can take more chars.

        % Need more chars to check
        {A1, Alen1, [], L1, C1, S1} ->
            {more,
                {tokens, S1, L1, C1, Tcs, Alen1, Tline, Tcol, Ts, A1, Alen1}};
        % Take what we got
        {A1, Alen1, Ics1, L1, C1, _S1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(
                Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts
            );
        %% After a non-accepting state, maybe reach accept state later.

        % Need more chars to check
        {A1, Alen1, Tlen1, [], L1, C1, S1} ->
            {more,
                {tokens, S1, L1, C1, Tcs, Tlen1, Tline, Tcol, Ts, A1, Alen1}};
        % No token match
        {reject, _Alen1, Tlen1, eof, L1, C1, _S1} ->
            %% Check for partial token which is error, no need to skip here.
            Ret =
                if
                    Tlen1 > 0 ->
                        {error,
                            {
                                {Tline, Tcol},
                                ?MODULE,
                                %% Skip eof tail in Tcs.
                                {illegal, yypre(Tcs, Tlen1)}
                            },
                            {L1, C1}};
                    Ts == [] ->
                        {eof, {L1, C1}};
                    true ->
                        {ok, yyrev(Ts), {L1, C1}}
                end,
            {done, Ret, eof};
        {reject, _Alen1, Tlen1, _Ics1, L1, C1, _S1} ->
            %% Skip rest of tokens.
            Error = {{L1, C1}, ?MODULE, {illegal, yypre(Tcs, Tlen1 + 1)}},
            skip_tokens(yysuf(Tcs, Tlen1 + 1), L1, C1, Error);
        {A1, Alen1, Tlen1, _Ics1, L1, _C1, _S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            tokens_cont(Tcs1, L2, C2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Column, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/5}).

tokens_cont(Rest, Line, Col, {token, T}, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, [T | Ts], reject, 0);
tokens_cont(Rest, Line, Col, {token, T, Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(
        yystate(),
        NewRest,
        Line,
        Col,
        NewRest,
        0,
        Line,
        Col,
        [T | Ts],
        reject,
        0
    );
tokens_cont(Rest, Line, Col, {end_token, T}, Ts) ->
    {done, {ok, yyrev(Ts, [T]), {Line, Col}}, Rest};
tokens_cont(Rest, Line, Col, {end_token, T, Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done, {ok, yyrev(Ts, [T]), {Line, Col}}, NewRest};
tokens_cont(Rest, Line, Col, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {skip_token, Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {error, S}, _Ts) ->
    skip_tokens(Rest, Line, Col, {{Line, Col}, ?MODULE, {user, S}}).

%% skip_tokens(InChars, Line, Col, Error) -> {done,{error,Error,{Line,Col}},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Col, Error) ->
    skip_tokens(yystate(), Ics, Line, Col, Ics, 0, Line, Col, Error, reject, 0).

%% skip_tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        % Accepting end state
        {A1, Alen1, Ics1, L1, C1} ->
            skip_cont(
                Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error
            );
        % After an accepting state
        {A1, Alen1, [], L1, C1, S1} ->
            {more,
                {skip_tokens, S1, L1, C1, Tcs, Alen1, Tline, Tcol, Error, A1,
                    Alen1}};
        {A1, Alen1, Ics1, L1, C1, _S1} ->
            skip_cont(
                Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error
            );
        % After a non-accepting state
        {A1, Alen1, Tlen1, [], L1, C1, S1} ->
            {more,
                {skip_tokens, S1, L1, C1, Tcs, Tlen1, Tline, Tcol, Error, A1,
                    Alen1}};
        {reject, _Alen1, _Tlen1, eof, L1, C1, _S1} ->
            {done, {error, Error, {L1, C1}}, eof};
        {reject, _Alen1, Tlen1, _Ics1, L1, C1, _S1} ->
            skip_tokens(yysuf(Tcs, Tlen1 + 1), L1, C1, Error);
        {A1, Alen1, Tlen1, _Ics1, L1, C1, _S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, C1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Col, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/5}).

skip_cont(Rest, Line, Col, {token, _T}, Error) ->
    skip_tokens(
        yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0
    );
skip_cont(Rest, Line, Col, {token, _T, Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(
        yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0
    );
skip_cont(Rest, Line, Col, {end_token, _T}, Error) ->
    {done, {error, Error, {Line, Col}}, Rest};
skip_cont(Rest, Line, Col, {end_token, _T, Push}, Error) ->
    NewRest = Push ++ Rest,
    {done, {error, Error, {Line, Col}}, NewRest};
skip_cont(Rest, Line, Col, skip_token, Error) ->
    skip_tokens(
        yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0
    );
skip_cont(Rest, Line, Col, {skip_token, Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(
        yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0
    );
skip_cont(Rest, Line, Col, {error, _S}, Error) ->
    skip_tokens(
        yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0
    ).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n | Cs], L) -> adjust_line(T - 1, A, Cs, L - 1);
adjust_line(T, A, [_ | Cs], L) -> adjust_line(T - 1, A, Cs, L).

%% adjust_col(Chars, AcceptLength, Col) -> NewCol
%% Handle newlines, tabs and unicode chars.
adjust_col(_, 0, Col) ->
    Col;
adjust_col([$\n | R], L, _) ->
    adjust_col(R, L - 1, 1);
adjust_col([$\t | R], L, Col) ->
    adjust_col(R, L - 1, tab_forward(Col) + 1);
adjust_col([C | R], L, Col) when C >= 0 andalso C =< 16#7F ->
    adjust_col(R, L - 1, Col + 1);
adjust_col([C | R], L, Col) when C >= 16#80 andalso C =< 16#7FF ->
    adjust_col(R, L - 1, Col + 2);
adjust_col([C | R], L, Col) when C >= 16#800 andalso C =< 16#FFFF ->
    adjust_col(R, L - 1, Col + 3);
adjust_col([C | R], L, Col) when C >= 16#10000 andalso C =< 16#10FFFF ->
    adjust_col(R, L - 1, Col + 4).

tab_forward(C) ->
    D = C rem tab_size(),
    A = tab_size() - D,
    C + A.

tab_size() -> 8.

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, Col, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line, Col} |
%% {Action, AcceptLen, RestChars, Line, Col, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, Col, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, Col, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.erl", 410
).
yystate() -> 84.

yystate(87, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(87, Ics, Line, Col, Tlen + 1, 14, Tlen);
yystate(87, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(87, Ics, Line, Col, Tlen + 1, 14, Tlen);
yystate(87, Ics, Line, Col, Tlen, _, _) ->
    {14, Tlen, Ics, Line, Col, 87};
yystate(86, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(86, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(86, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 86};
yystate(85, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(81, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(85, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(85, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(85, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(85, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 85};
yystate(84, [124 | Ics], Line, Col, Tlen, _, _) ->
    yystate(80, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [96 | Ics], Line, Col, Tlen, _, _) ->
    yystate(76, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [87 | Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [85 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [86 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [84 | Ics], Line, Col, Tlen, _, _) ->
    yystate(44, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [83 | Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [82 | Ics], Line, Col, Tlen, _, _) ->
    yystate(47, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [71 | Ics], Line, Col, Tlen, _, _) ->
    yystate(67, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [70 | Ics], Line, Col, Tlen, _, _) ->
    yystate(85, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [69 | Ics], Line, Col, Tlen, _, _) ->
    yystate(53, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [67 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [68 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [66 | Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [65 | Ics], Line, Col, Tlen, _, _) ->
    yystate(42, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [64 | Ics], Line, Col, Tlen, _, _) ->
    yystate(58, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [35 | Ics], Line, Col, Tlen, _, _) ->
    yystate(62, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [34 | Ics], Line, Col, Tlen, _, _) ->
    yystate(66, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [33 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [32 | Ics], Line, Col, Tlen, _, _) ->
    yystate(82, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [10 | Ics], Line, _, Tlen, _, _) ->
    yystate(78, Ics, Line + 1, 1, Tlen + 1, 18, Tlen);
yystate(84, [9 | Ics], Line, Col, Tlen, _, _) ->
    yystate(82, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [C | Ics], Line, Col, Tlen, _, _) when C >= 36, C =< 63 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [C | Ics], Line, Col, Tlen, _, _) when C >= 72, C =< 81 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [C | Ics], Line, Col, Tlen, _, _) when C >= 88, C =< 95 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [C | Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 123 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, [C | Ics], Line, Col, Tlen, _, _) when C >= 125 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(84, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 84};
yystate(83, [32 | Ics], Line, Col, Tlen, _, _) ->
    yystate(87, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(83, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(83, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(83, [C | Ics], Line, Col, Tlen, _, _) when C >= 33 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(83, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 83};
yystate(82, [124 | Ics], Line, Col, Tlen, _, _) ->
    yystate(80, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [96 | Ics], Line, Col, Tlen, _, _) ->
    yystate(76, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [87 | Ics], Line, Col, Tlen, _, _) ->
    yystate(64, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [85 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [86 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [84 | Ics], Line, Col, Tlen, _, _) ->
    yystate(44, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [83 | Ics], Line, Col, Tlen, _, _) ->
    yystate(24, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [82 | Ics], Line, Col, Tlen, _, _) ->
    yystate(47, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [71 | Ics], Line, Col, Tlen, _, _) ->
    yystate(67, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [70 | Ics], Line, Col, Tlen, _, _) ->
    yystate(85, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [69 | Ics], Line, Col, Tlen, _, _) ->
    yystate(53, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [67 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [68 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [66 | Ics], Line, Col, Tlen, _, _) ->
    yystate(13, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [65 | Ics], Line, Col, Tlen, _, _) ->
    yystate(42, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [64 | Ics], Line, Col, Tlen, _, _) ->
    yystate(58, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [35 | Ics], Line, Col, Tlen, _, _) ->
    yystate(62, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [34 | Ics], Line, Col, Tlen, _, _) ->
    yystate(66, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [33 | Ics], Line, Col, Tlen, _, _) ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [32 | Ics], Line, Col, Tlen, _, _) ->
    yystate(82, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [9 | Ics], Line, Col, Tlen, _, _) ->
    yystate(82, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [C | Ics], Line, Col, Tlen, _, _) when C >= 36, C =< 63 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [C | Ics], Line, Col, Tlen, _, _) when C >= 72, C =< 81 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [C | Ics], Line, Col, Tlen, _, _) when C >= 88, C =< 95 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [C | Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 123 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, [C | Ics], Line, Col, Tlen, _, _) when C >= 125 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(82, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 82};
yystate(81, [97 | Ics], Line, Col, Tlen, _, _) ->
    yystate(77, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(81, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(81, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 96 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(81, [C | Ics], Line, Col, Tlen, _, _) when C >= 98 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(81, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 81};
yystate(80, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(80, Ics, Line, Col, Tlen + 1, 17, Tlen);
yystate(80, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(80, Ics, Line, Col, Tlen + 1, 17, Tlen);
yystate(80, Ics, Line, Col, Tlen, _, _) ->
    {17, Tlen, Ics, Line, Col, 80};
yystate(79, [110 | Ics], Line, Col, Tlen, _, _) ->
    yystate(83, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(79, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(79, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(79, [C | Ics], Line, Col, Tlen, _, _) when C >= 111 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(79, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 79};
yystate(78, Ics, Line, Col, Tlen, _, _) ->
    {1, Tlen, Ics, Line, Col};
yystate(77, [116 | Ics], Line, Col, Tlen, _, _) ->
    yystate(73, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(77, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(77, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 115 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(77, [C | Ics], Line, Col, Tlen, _, _) when C >= 117 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(77, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 77};
yystate(76, [96 | Ics], Line, Col, Tlen, _, _) ->
    yystate(72, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(76, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(76, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 95 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(76, [C | Ics], Line, Col, Tlen, _, _) when C >= 97 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(76, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 76};
yystate(75, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(79, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(75, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(75, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(75, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(75, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 75};
yystate(74, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 15, Tlen);
yystate(74, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 15, Tlen);
yystate(74, Ics, Line, Col, Tlen, _, _) ->
    {15, Tlen, Ics, Line, Col, 74};
yystate(73, [117 | Ics], Line, Col, Tlen, _, _) ->
    yystate(69, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(73, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(73, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 116 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(73, [C | Ics], Line, Col, Tlen, _, _) when C >= 118 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(73, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 73};
yystate(72, [96 | Ics], Line, Col, Tlen, _, _) ->
    yystate(68, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(72, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(72, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 95 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(72, [C | Ics], Line, Col, Tlen, _, _) when C >= 97 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(72, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 72};
yystate(71, [118 | Ics], Line, Col, Tlen, _, _) ->
    yystate(75, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(71, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(71, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 117 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(71, [C | Ics], Line, Col, Tlen, _, _) when C >= 119 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(71, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 71};
yystate(70, [34 | Ics], Line, Col, Tlen, _, _) ->
    yystate(74, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(70, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(70, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(70, [C | Ics], Line, Col, Tlen, _, _) when C >= 35 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(70, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 70};
yystate(69, [114 | Ics], Line, Col, Tlen, _, _) ->
    yystate(65, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(69, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(69, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 113 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(69, [C | Ics], Line, Col, Tlen, _, _) when C >= 115 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(69, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 69};
yystate(68, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 16, Tlen);
yystate(68, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 16, Tlen);
yystate(68, Ics, Line, Col, Tlen, _, _) ->
    {16, Tlen, Ics, Line, Col, 68};
yystate(67, [105 | Ics], Line, Col, Tlen, _, _) ->
    yystate(71, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(67, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(67, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 104 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(67, [C | Ics], Line, Col, Tlen, _, _) when C >= 106 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(67, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 67};
yystate(66, [34 | Ics], Line, Col, Tlen, _, _) ->
    yystate(70, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(66, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(66, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(66, [C | Ics], Line, Col, Tlen, _, _) when C >= 35 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(66, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 66};
yystate(65, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(61, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(65, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(65, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(65, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(65, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 65};
yystate(64, [104 | Ics], Line, Col, Tlen, _, _) ->
    yystate(60, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(64, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(64, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 103 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(64, [C | Ics], Line, Col, Tlen, _, _) when C >= 105 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(64, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 64};
yystate(63, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(63, Ics, Line, Col, Tlen + 1, 5, Tlen);
yystate(63, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(63, Ics, Line, Col, Tlen + 1, 5, Tlen);
yystate(63, Ics, Line, Col, Tlen, _, _) ->
    {5, Tlen, Ics, Line, Col, 63};
yystate(62, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(62, Ics, Line, Col, Tlen + 1, 2, Tlen);
yystate(62, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(62, Ics, Line, Col, Tlen + 1, 2, Tlen);
yystate(62, Ics, Line, Col, Tlen, _, _) ->
    {2, Tlen, Ics, Line, Col, 62};
yystate(61, [58 | Ics], Line, Col, Tlen, _, _) ->
    yystate(57, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(61, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(61, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 57 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(61, [C | Ics], Line, Col, Tlen, _, _) when C >= 59 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(61, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 61};
yystate(60, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(56, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(60, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(60, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(60, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(60, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 60};
yystate(59, [58 | Ics], Line, Col, Tlen, _, _) ->
    yystate(63, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(59, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(59, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 57 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(59, [C | Ics], Line, Col, Tlen, _, _) when C >= 59 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(59, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 59};
yystate(58, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(58, Ics, Line, Col, Tlen + 1, 0, Tlen);
yystate(58, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(58, Ics, Line, Col, Tlen + 1, 0, Tlen);
yystate(58, Ics, Line, Col, Tlen, _, _) ->
    {0, Tlen, Ics, Line, Col, 58};
yystate(57, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(57, Ics, Line, Col, Tlen + 1, 3, Tlen);
yystate(57, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(57, Ics, Line, Col, Tlen + 1, 3, Tlen);
yystate(57, Ics, Line, Col, Tlen, _, _) ->
    {3, Tlen, Ics, Line, Col, 57};
yystate(56, [110 | Ics], Line, Col, Tlen, _, _) ->
    yystate(52, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(56, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(56, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(56, [C | Ics], Line, Col, Tlen, _, _) when C >= 111 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(56, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 56};
yystate(55, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(59, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(55, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(55, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(55, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(55, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 55};
yystate(54, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(54, Ics, Line, Col, Tlen + 1, 10, Tlen);
yystate(54, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(54, Ics, Line, Col, Tlen + 1, 10, Tlen);
yystate(54, Ics, Line, Col, Tlen, _, _) ->
    {10, Tlen, Ics, Line, Col, 54};
yystate(53, [120 | Ics], Line, Col, Tlen, _, _) ->
    yystate(49, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(53, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(53, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 119 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(53, [C | Ics], Line, Col, Tlen, _, _) when C >= 121 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(53, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 53};
yystate(52, [32 | Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(52, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(52, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(52, [C | Ics], Line, Col, Tlen, _, _) when C >= 33 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(52, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 52};
yystate(51, [108 | Ics], Line, Col, Tlen, _, _) ->
    yystate(55, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(51, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(51, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 107 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(51, [C | Ics], Line, Col, Tlen, _, _) when C >= 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(51, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 51};
yystate(50, [32 | Ics], Line, Col, Tlen, _, _) ->
    yystate(54, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(50, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(50, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(50, [C | Ics], Line, Col, Tlen, _, _) when C >= 33 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(50, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 50};
yystate(49, [97 | Ics], Line, Col, Tlen, _, _) ->
    yystate(45, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(49, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(49, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 96 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(49, [C | Ics], Line, Col, Tlen, _, _) when C >= 98 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(49, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 49};
yystate(48, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(48, Ics, Line, Col, Tlen + 1, 12, Tlen);
yystate(48, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(48, Ics, Line, Col, Tlen + 1, 12, Tlen);
yystate(48, Ics, Line, Col, Tlen, _, _) ->
    {12, Tlen, Ics, Line, Col, 48};
yystate(47, [117 | Ics], Line, Col, Tlen, _, _) ->
    yystate(51, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(47, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(47, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 116 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(47, [C | Ics], Line, Col, Tlen, _, _) when C >= 118 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(47, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 47};
yystate(46, [100 | Ics], Line, Col, Tlen, _, _) ->
    yystate(50, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(46, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(46, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 99 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(46, [C | Ics], Line, Col, Tlen, _, _) when C >= 101 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(46, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 46};
yystate(45, [109 | Ics], Line, Col, Tlen, _, _) ->
    yystate(41, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(45, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(45, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 108 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(45, [C | Ics], Line, Col, Tlen, _, _) when C >= 110 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(45, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 45};
yystate(44, [104 | Ics], Line, Col, Tlen, _, _) ->
    yystate(40, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(44, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(44, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 103 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(44, [C | Ics], Line, Col, Tlen, _, _) when C >= 105 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(44, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 44};
yystate(43, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(43, Ics, Line, Col, Tlen + 1, 6, Tlen);
yystate(43, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(43, Ics, Line, Col, Tlen + 1, 6, Tlen);
yystate(43, Ics, Line, Col, Tlen, _, _) ->
    {6, Tlen, Ics, Line, Col, 43};
yystate(42, [110 | Ics], Line, Col, Tlen, _, _) ->
    yystate(46, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(42, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(42, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(42, [C | Ics], Line, Col, Tlen, _, _) when C >= 111 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(42, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 42};
yystate(41, [112 | Ics], Line, Col, Tlen, _, _) ->
    yystate(37, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(41, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(41, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 111 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(41, [C | Ics], Line, Col, Tlen, _, _) when C >= 113 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(41, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 41};
yystate(40, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(40, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(40, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(40, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(40, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 40};
yystate(39, [58 | Ics], Line, Col, Tlen, _, _) ->
    yystate(43, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(39, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(39, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 57 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(39, [C | Ics], Line, Col, Tlen, _, _) when C >= 59 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(39, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 39};
yystate(38, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Col, Tlen + 1, 4, Tlen);
yystate(38, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(38, Ics, Line, Col, Tlen + 1, 4, Tlen);
yystate(38, Ics, Line, Col, Tlen, _, _) ->
    {4, Tlen, Ics, Line, Col, 38};
yystate(37, [108 | Ics], Line, Col, Tlen, _, _) ->
    yystate(33, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(37, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(37, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 107 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(37, [C | Ics], Line, Col, Tlen, _, _) when C >= 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(37, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 37};
yystate(36, [110 | Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(36, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(36, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(36, [C | Ics], Line, Col, Tlen, _, _) when C >= 111 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(36, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 36};
yystate(35, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(39, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(35, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(35, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(35, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(35, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 35};
yystate(34, [58 | Ics], Line, Col, Tlen, _, _) ->
    yystate(38, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(34, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(34, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 57 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(34, [C | Ics], Line, Col, Tlen, _, _) when C >= 59 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(34, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 34};
yystate(33, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(29, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(33, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(33, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(33, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(33, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 33};
yystate(32, [32 | Ics], Line, Col, Tlen, _, _) ->
    yystate(28, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(32, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(32, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(32, [C | Ics], Line, Col, Tlen, _, _) when C >= 33 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(32, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 32};
yystate(31, [110 | Ics], Line, Col, Tlen, _, _) ->
    yystate(35, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(31, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(31, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(31, [C | Ics], Line, Col, Tlen, _, _) when C >= 111 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(31, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 31};
yystate(30, [100 | Ics], Line, Col, Tlen, _, _) ->
    yystate(34, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(30, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(30, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 99 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(30, [C | Ics], Line, Col, Tlen, _, _) when C >= 101 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(30, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 30};
yystate(29, [115 | Ics], Line, Col, Tlen, _, _) ->
    yystate(25, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(29, [58 | Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(29, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(29, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 57 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(29, [C | Ics], Line, Col, Tlen, _, _) when C >= 59, C =< 114 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(29, [C | Ics], Line, Col, Tlen, _, _) when C >= 116 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(29, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 29};
yystate(28, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(28, Ics, Line, Col, Tlen + 1, 13, Tlen);
yystate(28, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(28, Ics, Line, Col, Tlen + 1, 13, Tlen);
yystate(28, Ics, Line, Col, Tlen, _, _) ->
    {13, Tlen, Ics, Line, Col, 28};
yystate(27, [105 | Ics], Line, Col, Tlen, _, _) ->
    yystate(31, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(27, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(27, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 104 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(27, [C | Ics], Line, Col, Tlen, _, _) when C >= 106 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(27, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 27};
yystate(26, [110 | Ics], Line, Col, Tlen, _, _) ->
    yystate(30, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(26, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(26, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(26, [C | Ics], Line, Col, Tlen, _, _) when C >= 111 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(26, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 26};
yystate(25, [58 | Ics], Line, Col, Tlen, _, _) ->
    yystate(21, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(25, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(25, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 57 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(25, [C | Ics], Line, Col, Tlen, _, _) when C >= 59 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(25, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 25};
yystate(24, [99 | Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(24, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(24, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 98 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(24, [C | Ics], Line, Col, Tlen, _, _) when C >= 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(24, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 24};
yystate(23, [108 | Ics], Line, Col, Tlen, _, _) ->
    yystate(27, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(23, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(23, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 107 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(23, [C | Ics], Line, Col, Tlen, _, _) when C >= 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(23, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 23};
yystate(22, [117 | Ics], Line, Col, Tlen, _, _) ->
    yystate(26, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(22, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(22, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 116 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(22, [C | Ics], Line, Col, Tlen, _, _) when C >= 118 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(22, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 22};
yystate(21, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Col, Tlen + 1, 9, Tlen);
yystate(21, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(21, Ics, Line, Col, Tlen + 1, 9, Tlen);
yystate(21, Ics, Line, Col, Tlen, _, _) ->
    {9, Tlen, Ics, Line, Col, 21};
yystate(20, [101 | Ics], Line, Col, Tlen, _, _) ->
    yystate(16, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(20, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(20, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(20, [C | Ics], Line, Col, Tlen, _, _) when C >= 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(20, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 20};
yystate(19, [116 | Ics], Line, Col, Tlen, _, _) ->
    yystate(23, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(19, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(19, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 115 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(19, [C | Ics], Line, Col, Tlen, _, _) when C >= 117 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(19, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 19};
yystate(18, [111 | Ics], Line, Col, Tlen, _, _) ->
    yystate(22, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(18, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(18, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 110 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(18, [C | Ics], Line, Col, Tlen, _, _) when C >= 112 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(18, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 18};
yystate(17, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(17, Ics, Line, Col, Tlen + 1, 8, Tlen);
yystate(17, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(17, Ics, Line, Col, Tlen + 1, 8, Tlen);
yystate(17, Ics, Line, Col, Tlen, _, _) ->
    {8, Tlen, Ics, Line, Col, 17};
yystate(16, [110 | Ics], Line, Col, Tlen, _, _) ->
    yystate(12, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(16, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(16, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 109 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(16, [C | Ics], Line, Col, Tlen, _, _) when C >= 111 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(16, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 16};
yystate(15, [117 | Ics], Line, Col, Tlen, _, _) ->
    yystate(19, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(15, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(15, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 116 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(15, [C | Ics], Line, Col, Tlen, _, _) when C >= 118 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(15, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 15};
yystate(14, [114 | Ics], Line, Col, Tlen, _, _) ->
    yystate(18, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(14, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(14, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 113 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(14, [C | Ics], Line, Col, Tlen, _, _) when C >= 115 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(14, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 14};
yystate(13, [117 | Ics], Line, Col, Tlen, _, _) ->
    yystate(9, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(13, [97 | Ics], Line, Col, Tlen, _, _) ->
    yystate(2, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(13, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(13, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 96 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(13, [C | Ics], Line, Col, Tlen, _, _) when C >= 98, C =< 116 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(13, [C | Ics], Line, Col, Tlen, _, _) when C >= 118 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(13, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 13};
yystate(12, [97 | Ics], Line, Col, Tlen, _, _) ->
    yystate(8, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(12, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(12, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 96 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(12, [C | Ics], Line, Col, Tlen, _, _) when C >= 98 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(12, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 12};
yystate(11, [79 | Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(11, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(11, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 78 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(11, [C | Ics], Line, Col, Tlen, _, _) when C >= 80 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(11, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 11};
yystate(10, [103 | Ics], Line, Col, Tlen, _, _) ->
    yystate(14, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(10, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(10, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 102 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(10, [C | Ics], Line, Col, Tlen, _, _) when C >= 104 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(10, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 10};
yystate(9, [116 | Ics], Line, Col, Tlen, _, _) ->
    yystate(5, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(9, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(9, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 115 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(9, [C | Ics], Line, Col, Tlen, _, _) when C >= 117 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(9, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 9};
yystate(8, [114 | Ics], Line, Col, Tlen, _, _) ->
    yystate(4, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(8, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(8, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 113 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(8, [C | Ics], Line, Col, Tlen, _, _) when C >= 115 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(8, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 8};
yystate(7, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(7, Ics, Line, Col, Tlen + 1, 7, Tlen);
yystate(7, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(7, Ics, Line, Col, Tlen + 1, 7, Tlen);
yystate(7, Ics, Line, Col, Tlen, _, _) ->
    {7, Tlen, Ics, Line, Col, 7};
yystate(6, [107 | Ics], Line, Col, Tlen, _, _) ->
    yystate(10, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(6, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(6, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 106 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(6, [C | Ics], Line, Col, Tlen, _, _) when C >= 108 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(6, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 6};
yystate(5, [32 | Ics], Line, Col, Tlen, _, _) ->
    yystate(1, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(5, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(5, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(5, [C | Ics], Line, Col, Tlen, _, _) when C >= 33 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(5, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 5};
yystate(4, [105 | Ics], Line, Col, Tlen, _, _) ->
    yystate(0, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(4, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(4, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 104 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(4, [C | Ics], Line, Col, Tlen, _, _) when C >= 106 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(4, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 4};
yystate(3, [58 | Ics], Line, Col, Tlen, _, _) ->
    yystate(7, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(3, [32 | Ics], Line, Col, Tlen, _, _) ->
    yystate(11, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(3, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(3, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 31 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(3, [C | Ics], Line, Col, Tlen, _, _) when C >= 33, C =< 57 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(3, [C | Ics], Line, Col, Tlen, _, _) when C >= 59 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(3, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 3};
yystate(2, [99 | Ics], Line, Col, Tlen, _, _) ->
    yystate(6, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(2, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(2, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 98 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(2, [C | Ics], Line, Col, Tlen, _, _) when C >= 100 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(2, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 2};
yystate(1, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(1, Ics, Line, Col, Tlen + 1, 11, Tlen);
yystate(1, [C | Ics], Line, Col, Tlen, _, _) when C >= 11 ->
    yystate(1, Ics, Line, Col, Tlen + 1, 11, Tlen);
yystate(1, Ics, Line, Col, Tlen, _, _) ->
    {11, Tlen, Ics, Line, Col, 1};
yystate(0, [111 | Ics], Line, Col, Tlen, _, _) ->
    yystate(3, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(0, [C | Ics], Line, Col, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(0, [C | Ics], Line, Col, Tlen, _, _) when C >= 11, C =< 110 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(0, [C | Ics], Line, Col, Tlen, _, _) when C >= 112 ->
    yystate(86, Ics, Line, Col, Tlen + 1, 18, Tlen);
yystate(0, Ics, Line, Col, Tlen, _, _) ->
    {18, Tlen, Ics, Line, Col, 0};
yystate(S, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action, Alen, Tlen, Ics, Line, Col, S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine, TokenCol) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine, TokenCol);
yyaction(1, _, _, _, _) ->
    yyaction_1();
yyaction(2, _, _, _, _) ->
    yyaction_2();
yyaction(3, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine, TokenCol);
yyaction(4, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine, TokenCol);
yyaction(5, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine, TokenCol);
yyaction(6, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine, TokenCol);
yyaction(7, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine, TokenCol);
yyaction(8, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine, TokenCol);
yyaction(9, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine, TokenCol);
yyaction(10, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine, TokenCol);
yyaction(11, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine, TokenCol);
yyaction(12, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine, TokenCol);
yyaction(13, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine, TokenCol);
yyaction(14, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine, TokenCol);
yyaction(15, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine, TokenCol);
yyaction(16, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine, TokenCol);
yyaction(17, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine, TokenCol);
yyaction(18, TokenLen, YYtcs, TokenLine, TokenCol) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine, TokenCol);
yyaction(_, _, _, _, _) ->
    error.

-compile({inline, yyaction_0/3}).
-file("/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 7).
yyaction_0(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, {tags, TokenLoc, tags(TokenChars)}}.

-compile({inline, yyaction_1/0}).
-file("/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 8).
yyaction_1() ->
    skip_token.

-compile({inline, yyaction_2/0}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 10
).
yyaction_2() ->
    skip_token.

-compile({inline, yyaction_3/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 11
).
yyaction_3(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Feature", TokenLoc, TokenChars)}.

-compile({inline, yyaction_4/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 12
).
yyaction_4(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Background", TokenLoc, TokenChars)}.

-compile({inline, yyaction_5/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 13
).
yyaction_5(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Rule", TokenLoc, TokenChars)}.

-compile({inline, yyaction_6/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 14
).
yyaction_6(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Scenario Outline", TokenLoc, TokenChars)}.

-compile({inline, yyaction_7/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 15
).
yyaction_7(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Scenario", TokenLoc, TokenChars)}.

-compile({inline, yyaction_8/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 16
).
yyaction_8(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Example", TokenLoc, TokenChars)}.

-compile({inline, yyaction_9/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 17
).
yyaction_9(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Examples", TokenLoc, TokenChars)}.

-compile({inline, yyaction_10/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 18
).
yyaction_10(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("And", TokenLoc, TokenChars)}.

-compile({inline, yyaction_11/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 19
).
yyaction_11(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("But", TokenLoc, TokenChars)}.

-compile({inline, yyaction_12/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 20
).
yyaction_12(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("When", TokenLoc, TokenChars)}.

-compile({inline, yyaction_13/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 21
).
yyaction_13(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Then", TokenLoc, TokenChars)}.

-compile({inline, yyaction_14/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 22
).
yyaction_14(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, statement("Given", TokenLoc, TokenChars)}.

-compile({inline, yyaction_15/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 23
).
yyaction_15(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, {doc_quote, TokenLoc, TokenChars}}.

-compile({inline, yyaction_16/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 24
).
yyaction_16(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, {doc_tick, TokenLoc, TokenChars}}.

-compile({inline, yyaction_17/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 25
).
yyaction_17(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, {table_row, TokenLoc, TokenChars}}.

-compile({inline, yyaction_18/3}).
-file(
    "/Users/alind/Developer/Code/cucumis/src/cucumis_gherkin_scanner.xrl", 26
).
yyaction_18(TokenChars, TokenLine, TokenCol) ->
    TokenLoc = {TokenLine, TokenCol},
    {token, {text, TokenLoc, TokenChars}}.
-file(
    "/Users/alind/.local/share/mise/installs/erlang/28.2/lib/parsetools-2.7/include/leexinc.hrl",
    377
).
